"""
This type stub file was generated by pyright.
"""

import click
from pathlib import Path

"""Entry point for the CLI application."""
@click.command(context_settings={ "help_option_names": ["-h", "--help"] })
@click.argument("directory", nargs=1, default=Path.cwd())
@click.option("-l", is_flag=True, default=False, help="List all the files that will be nuked")
@click.option("-y", is_flag=True, is_eager=True, default=False, help="Flag to confirm nuking")
def main(directory: str, l: bool, y: bool) -> None:
    """
    Nuke (aka delete the contents of) the DIRECTORY specified.
    Default directory is the current directory.
    """
    ...

