"""
This type stub file was generated by pyright.
"""

from pathlib import Path

"""Utilities for getting directory tree."""
def get_dirtree(directory: Path) -> tuple[list[dict[str, object]], list[str]]:
    """
    Get the directory tree of the `directory`.
    :param directory: The root directory from where to generate the directory tree.
    :return: The list of paths with appropriate indenting, and the list of ignore patterns.
    """
    ...

