"""
This type stub file was generated by pyright.
"""

from pathlib import Path

"""Main command line tool to nuke a directory."""
def get_file_list(directory: Path) -> tuple[list[Path], list[str]]:
    """
    Retrieve all the files in the directory tree that are to be nuked,
    as well as the list of file patterns to ignore.
    :param directory: The root directory of the directory tree to nuke.
    :return: The list of all files to be deleted and the list of all ignore patterns.
    """
    ...

def ignore_paths(path_list: list[dict[str, object]], ignore_patterns: list[str], processor: callable = ...) -> list[dict[str, object]]: # type: ignore
    """
    Go through the `path_list` and ignore any paths that match the patterns in `ignore_patterns`
    :param path_list: List of file/directory paths.
    :param ignore_patterns: List of nukeignore patterns.
    :param processor: Function to apply to every element in the path list before performing match.
    :return: The updated path list
    """
    ...

def list_files_tree(directory: Path) -> list[dict[str, object]]:
    """
    List all the files to be nuked in a nice directory tree.
    :param directory: The root directory to list from.
    :return: The list of files to be nuked. Each element of the list is a dict of filename and path.
    """
    ...

def delete(x: Path) -> None:
    """Convenience method to delete file or directory.

    Args:
        x (Path): The filesystem object to delete.
    """
    ...

def nuke(directory: Path) -> None:
    """This is where all the nuking happens."""
    ...

