"""
This type stub file was generated by pyright.
"""

from pathlib import Path

"""Utilities module."""
def fg(text: str, color: int) -> str:
    """Set text to foregound color."""
    ...

def bg(text: str, color: int) -> str:
    """Set text to background color."""
    ...

def get_colorized(path: Path) -> object:
    """Colorize path name based on type."""
    ...

def parse_ignore_file(filename: str, dirname: Path) -> list[str]:
    """
    Parse the ignore file and return a list of ignore patterns.
    Each pattern has the complete file path so we can take into account ignore at different levels.
    :param filename: The name of the ignore file.
    :param dirname: The directory Path where the ignore file was found.
    :return: List of ignore patterns.
    """
    ...

